apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm/
    repoUrl: https://github.com/psharneja/udacity-swifttech-techtrends
    targetRevision: HEAD
